changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation and maintenance
      labels:
        - documentation
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
